// Languages supported by both default hosted routes (Groq Whisper Turbo and
// Soniox async v5). `popular` only controls the short list shown first in the
// selector; it has no effect on provider routing.
export const LANGUAGES = [
  { code: "en", name: "English", popular: true },
  { code: "zh", name: "Chinese", popular: true },
  { code: "de", name: "German", popular: true },
  { code: "es", name: "Spanish", popular: true },
  { code: "ru", name: "Russian", popular: true },
  { code: "ko", name: "Korean", popular: true },
  { code: "fr", name: "French", popular: true },
  { code: "ja", name: "Japanese", popular: true },
  { code: "pt", name: "Portuguese", popular: true },
  { code: "it", name: "Italian", popular: true },
  { code: "ar", name: "Arabic", popular: true },
  { code: "af", name: "Afrikaans" },
  { code: "sq", name: "Albanian" },
  { code: "az", name: "Azerbaijani" },
  { code: "eu", name: "Basque" },
  { code: "be", name: "Belarusian" },
  { code: "bn", name: "Bengali" },
  { code: "bs", name: "Bosnian" },
  { code: "bg", name: "Bulgarian" },
  { code: "ca", name: "Catalan" },
  { code: "hr", name: "Croatian" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "nl", name: "Dutch" },
  { code: "et", name: "Estonian" },
  { code: "fi", name: "Finnish" },
  { code: "gl", name: "Galician" },
  { code: "el", name: "Greek" },
  { code: "gu", name: "Gujarati" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "hu", name: "Hungarian" },
  { code: "id", name: "Indonesian" },
  { code: "kn", name: "Kannada" },
  { code: "kk", name: "Kazakh" },
  { code: "lv", name: "Latvian" },
  { code: "lt", name: "Lithuanian" },
  { code: "mk", name: "Macedonian" },
  { code: "ms", name: "Malay" },
  { code: "ml", name: "Malayalam" },
  { code: "mr", name: "Marathi" },
  { code: "no", name: "Norwegian" },
  { code: "fa", name: "Persian" },
  { code: "pl", name: "Polish" },
  { code: "pa", name: "Punjabi" },
  { code: "ro", name: "Romanian" },
  { code: "sr", name: "Serbian" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "sw", name: "Swahili" },
  { code: "sv", name: "Swedish" },
  { code: "tl", name: "Tagalog" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" },
  { code: "tr", name: "Turkish" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "vi", name: "Vietnamese" },
  { code: "cy", name: "Welsh" },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"];

const CODES = new Set(LANGUAGES.map((language) => language.code));

export function isLanguageCode(value: string): value is LanguageCode {
  return CODES.has(value as LanguageCode);
}
