import { eq } from "drizzle-orm";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { jobs, transcripts } from "@/lib/schema";
import { isTier } from "@/lib/pricing";
import { getSettings } from "@/lib/settings";

export const dynamic = "force-dynamic";

const SHARE_ID = /^[A-Za-z0-9_-]{16,64}$/;

function fmt(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

async function load(shareId: string) {
  if (!SHARE_ID.test(shareId)) return null;
  const [row] = await db
    .select({ job: jobs, transcript: transcripts })
    .from(jobs)
    .innerJoin(transcripts, eq(transcripts.jobId, jobs.id))
    .where(eq(jobs.shareId, shareId))
    .limit(1);
  if (!row) return null;
  const settings = await getSettings();
  const features = isTier(row.job.tier)
    ? settings.tierFeatures[row.job.tier]
    : settings.tierFeatures.standard;
  return features.publicSharing ? { ...row, features } : null;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ shareId: string }>;
}): Promise<Metadata> {
  const { shareId } = await params;
  const row = await load(shareId);
  const title = row?.job.outputName ?? "Shared transcript";
  return { title, robots: { index: false, follow: false } };
}

export default async function SharePage({
  params,
}: {
  params: Promise<{ shareId: string }>;
}) {
  const { shareId } = await params;
  const row = await load(shareId);
  if (!row) notFound();

  const { job, transcript, features } = row;
  const title = job.outputName ?? "Transcript";

  return (
    <div className="mx-auto max-w-3xl py-10">
      <p className="text-xs font-medium uppercase tracking-wide text-muted">
        Shared transcript
      </p>
      <h1 className="mt-1 max-w-2xl text-2xl font-semibold">{title}</h1>
      <p className="mt-1 text-sm text-muted capitalize">
        {job.tier}
        {job.durationSeconds ? ` · ${fmt(job.durationSeconds)} long` : ""}
        {job.language ? ` · ${job.language}` : ""}
      </p>

      <aside className="status-info mt-6" aria-labelledby="shared-ai-note">
        <h2 id="shared-ai-note" className="font-semibold">
          Automatic transcript — verify important details
        </h2>
        <p className="mt-1">
          {job.resultSource === "same-account-cache"
            ? "The owner reused an earlier result from their account."
            : <>Generated by {job.provider ?? "the configured speech provider"}{job.model ? <> using {job.model}</> : null}.</>}{" "}
          Names, numbers, quotations, and speaker labels can be wrong.
        </p>
      </aside>

      {(features.textExport || features.subtitleExport) && (
      <div className="mt-6 flex flex-wrap gap-3">
        {(
          [
            ["txt", "Text file"],
            ["srt", "Subtitles (SRT)"],
            ["vtt", "Subtitles (VTT)"],
          ] as const
        ).filter(([format]) =>
          format === "txt" ? features.textExport : features.subtitleExport,
        ).map(([format, label]) => (
          <a
            key={format}
            href={`/api/share/${shareId}/download?format=${format}`}
            className="button-secondary"
          >
            <span aria-hidden="true">↓</span> {label}
          </a>
        ))}
      </div>
      )}

      <article aria-label="Shared transcript" className="mt-6 space-y-5 border-y border-line py-6">
        {transcript.segments.map((seg, i) => {
          const showSpeaker =
            seg.speaker && seg.speaker !== transcript.segments[i - 1]?.speaker;
          return (
            <div key={i}>
              {showSpeaker && (
                <p className="mt-2 text-xs font-semibold text-brand">{seg.speaker}</p>
              )}
              <p className="text-base leading-7 [overflow-wrap:anywhere]">
                <span className="mr-3 select-none font-mono text-sm text-muted">
                  {fmt(seg.start)}
                </span>
                {seg.text}
              </p>
            </div>
          );
        })}
      </article>

      <p className="mt-8 text-sm text-muted">
        Transcribed with{" "}
        <Link href="/" className="text-brand hover:underline">
          Transcribe
        </Link>
        {" "}— reviewable speech-to-text with timestamps.
      </p>
    </div>
  );
}
